{
 "title": "Sorting Payload Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(httpServerRequests.exception.None.method.POST.outcome.SUCCESS.status.200.uri._sort.count), 10, 8)"
    }
   ]
  },
  {
   "title": "400 Bad Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(httpServerRequests.exception.*.method.POST.outcome.CLIENT_ERROR.status.400.uri._sort.count), 10, 8)"
    }
   ]
  },
  { "title": "System Infomation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "target": "systemCpuUsage" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "processCpuUsage" }
   ]
  }
 ]
}